import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Header from "../../../components/common/header/Header";
import { trpc } from "../../../utils/trpc";

const Notit: NextPage = () => {
    const router = useRouter();
    const notitId = router.query["notitId"] as string;
    const { data, isError, isLoading } = trpc.useQuery([
        "notit.getOne",
        notitId,
    ]);

    const [notePages, setNotePages] = useState([]);

    useEffect(()=>{
        if(data){
            
        }
    },[data])

    if (isLoading) {
        return <div>Loading...</div>;
    }

    if (isError || !data) {
        return <div>Error...</div>;
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="">
                <h1>{data.name}</h1>
                <hr />
                <div></div>
            </main>
        </>
    );
};

export default Notit;
