import { NextPage } from "next";
import Head from "next/head";
import { FormEvent, useState } from "react";
import CalculatorButton from "../../../components/calculator/CalculatorButton";
import {
    getParentheses,
    solveParentheses,
} from "../../../components/calculator/helperFunctions";
import Header from "../../../components/common/header/Header";

const CalculatorHome: NextPage = () => {
    const [calcInput, setCalcInput] = useState("");

    const onSubmit = (e?: FormEvent<HTMLFormElement>) => {
        if (e) e.preventDefault();
        const result = parseInput(calcInput);
        setCalcInput(String(result));
    };

    const parseInput = (input: string) => {
        const result = getParentheses(input);
        const solve = solveParentheses({ ...result });
        return solve;
    };

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="bg-gray-400 w-96 mx-auto">
                <form onSubmit={onSubmit} className="w-full flex p-4">
                    <input
                        className="bg-gray p-2 text-2xl flex-1"
                        type="text"
                        value={calcInput}
                        onChange={(e) => setCalcInput(e.target.value)}
                    ></input>
                </form>
                <div className="grid grid-cols-4 w-full gap-2 p-4">
                    {[
                        "9",
                        "8",
                        "7",
                        "*",
                        "6",
                        "5",
                        "4",
                        "/",
                        "3",
                        "2",
                        "1",
                        "+",
                        "0",
                        "(",
                        ")",
                        "-",
                    ].map((item) => (
                        <CalculatorButton
                            key={item}
                            title={item}
                            onClick={() => setCalcInput(calcInput + item)}
                        />
                    ))}
                    <CalculatorButton
                        onClick={() => {
                            return;
                        }}
                        title=" "
                    />
                    <CalculatorButton
                        onClick={() => setCalcInput("")}
                        title="x"
                    />
                    <CalculatorButton
                        onClick={() => setCalcInput(calcInput.slice(0, -1))}
                        title="&#8592;"
                    />
                    <CalculatorButton onClick={() => onSubmit()} title="=" />
                </div>
            </main>
        </>
    );
};

export default CalculatorHome;
