import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Header from "../../../components/common/header/Header";

const Projects: NextPage = () => {
    const [startTime, setStartTime] = useState<number>(0);
    const [curTime, setCurTime] = useState<number>(0);
    const [running, setRunning] = useState(false);

    const startStopwatch = () => {
        setRunning(true);
        setStartTime(Date.now());
    };

    const stopStopwatch = () => {
        setRunning(false);
    };

    const resumeStopwatch = () => {
        setRunning(true);
    };

    const resetStopwatch = () => {
        setCurTime(0);
    };

    useEffect(() => {
        let interval: NodeJS.Timer;
        if (running) {
            interval = setInterval(() => {
                setCurTime(Date.now() - startTime);
            }, 10);
        }
        return () => clearInterval(interval);
    }, [running, startTime]);

    const formatTime = (time: number) => {
        return ("0" + time).slice(-2);
    };

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="bg-gray-800 rounded-2xl w-min mx-auto mt-8">
                <div className="flex text-center p-8 text-red-500 ">
                    <div className="mx-2">
                        <h2 className="font-semibold text-lg">Hours</h2>
                        <h2 className="text-4xl font-bold border-2 border-red-600 rounded-lg p-4">
                            {formatTime(Math.floor(curTime / 3600000))}
                        </h2>
                    </div>
                    <div className="mx-2">
                        <h2 className="font-semibold text-lg">Minutes</h2>
                        <h2 className="text-4xl font-bold border-2 border-red-600 rounded-lg p-4">
                            {formatTime(Math.floor(curTime / 60000) % 60)}
                        </h2>
                    </div>
                    <div className="mx-2">
                        <h2 className="font-semibold text-lg">Seconds</h2>
                        <h2 className="text-4xl font-bold border-2 border-red-600 rounded-lg p-4">
                            {formatTime(Math.floor(curTime / 1000) % 60)}
                        </h2>
                    </div>
                    <div className="mx-2">
                        <h2 className="font-semibold text-lg">Centiseconds</h2>
                        <h2 className="text-4xl font-bold border-2 border-red-600 rounded-lg p-4">
                            {("" + Math.floor(curTime % 1000)).slice(0, 2)}
                        </h2>
                    </div>
                </div>
                {running ? (
                    <div className="flex justify-evenly text-red-100 font-bold pb-4">
                        <button onClick={stopStopwatch}>Stop</button>
                    </div>
                ) : (
                    <div className="flex justify-evenly text-red-100 font-bold pb-4">
                        <button
                            className="mx-4 px-4 py-1 rounded-lg"
                            onClick={startStopwatch}
                        >
                            Start
                        </button>
                        {curTime !== 0 && (
                            <>
                                <button
                                    className="mx-4 px-4 py-1 rounded-lg"
                                    onClick={resumeStopwatch}
                                >
                                    Resume
                                </button>
                                <button
                                    className="mx-4 px-4 py-1 rounded-lg"
                                    onClick={resetStopwatch}
                                >
                                    Reset
                                </button>
                            </>
                        )}
                    </div>
                )}
            </main>
        </>
    );
};

export default Projects;
