import { NextPage } from "next";
import Header from "../components/common/header/Header";
import Head from "next/head";

const Contact: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
        </>
    );
};

export default Contact;
