import { NextPage } from "next";
import Head from "next/head";
import { useMemo, useState } from "react";
import Header from "../../../components/common/header/Header";
import Hand from "../../../components/rock-paper-scissors/Hand";

const Projects: NextPage = () => {
    const [choice, setChoice] = useState<"rock" | "paper" | "scissors">("rock");
    const [madeChoice, setMadeChoice] = useState(false);
    const [finished, setFinished] = useState("");

    const randomChoice = useMemo(() => {
        const choices = ["rock", "paper", "scissors"];
        const r = Math.random();
        if (r <= 0.33333) return choices[0];
        if (r <= 0.66666) return choices[1];
        return choices[2];
    }, [madeChoice]);

    const onFinished = () => {
        if (choice === "rock" && randomChoice === "rock") setFinished("draw");
        if (choice === "rock" && randomChoice === "paper") setFinished("loss");
        if (choice === "rock" && randomChoice === "scissors")
            setFinished("win");
        if (choice === "paper" && randomChoice === "rock") setFinished("win");
        if (choice === "paper" && randomChoice === "paper") setFinished("draw");
        if (choice === "paper" && randomChoice === "scissors")
            setFinished("loss");
        if (choice === "scissors" && randomChoice === "rock")
            setFinished("loss");
        if (choice === "scissors" && randomChoice === "paper")
            setFinished("win");
        if (choice === "scissors" && randomChoice === "scissors")
            setFinished("draw");
    };

    return (
        <div>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                {madeChoice ? (
                    <div>
                        <div className="w-full flex justify-between">
                            <div className="w-1/4 h-16 md:h-72 lg:h-96">
                                <Hand
                                    state={choice}
                                    direction="right"
                                    onFinished={onFinished}
                                />
                            </div>
                            <div className="w-1/4 h-16 md:h-72 lg:h-96">
                                <Hand
                                    state={
                                        randomChoice as
                                            | "rock"
                                            | "paper"
                                            | "scissors"
                                    }
                                    direction="left"
                                />
                            </div>
                        </div>
                        {finished !== "" && (
                            <div className="flex w-full flex-col text-center">
                                <h2 className="mt-32">
                                    It&apos;s a {finished}
                                </h2>
                                <button
                                    onClick={() => {
                                        setMadeChoice(false);
                                        setFinished("");
                                    }}
                                    className="border-2 border-blue-600 px-4 py-1 rounded-lg text-blue-600 w-max mx-auto mt-4"
                                >
                                    Try again?
                                </button>
                            </div>
                        )}
                    </div>
                ) : (
                    <div className="mx-auto w-full text-center">
                        <h1 className="text-xl font-bold mb-4">
                            Choose your fighter:
                        </h1>
                        <ul>
                            <li className="my-2">
                                <button
                                    onClick={() => {
                                        setChoice("rock");
                                        setMadeChoice(true);
                                    }}
                                    className="border-2 border-gray-800 px-4 py-1 bg-gray-800 text-white rounded-full"
                                >
                                    Rock
                                </button>
                            </li>
                            <li className="my-2">
                                <button
                                    onClick={() => {
                                        setChoice("paper");
                                        setMadeChoice(true);
                                    }}
                                    className="border-2 border-yellow-200 px-4 py-1 bg-yellow-200 rounded-full"
                                >
                                    Paper
                                </button>
                            </li>
                            <li className="my-2">
                                <button
                                    onClick={() => {
                                        setChoice("scissors");
                                        setMadeChoice(true);
                                    }}
                                    className="border-2 border-blue-600 px-4 py-1 bg-blue-600 text-white rounded-full"
                                >
                                    Scissors
                                </button>
                            </li>
                        </ul>
                    </div>
                )}
            </main>
        </div>
    );
};

export default Projects;
